<?php

namespace Database\Seeders;

use App\Enums\InvestorExperience;
use App\Enums\InvestorType;
use App\Enums\UserRole;
use App\Models\Category;
use App\Models\PreferredSector;
use App\Models\SubscriptionPackage;
use App\Models\User;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $sectorIds = PreferredSector::query()->orderBy('id')->pluck('id')->values();
        $categoryIds = Category::query()->orderBy('order')->pluck('id')->values();
        $packageIds = SubscriptionPackage::query()->orderBy('id')->pluck('id')->values();

        $users = [
            [
                'role' => UserRole::Investor,
                'first_name' => 'Maya',
                'last_name' => 'AlHarbi',
                'display_name' => 'Maya Capital',
                'country_code' => '965',
                'phone' => '50123456',
                'email' => 'maya.investor@bi.test',
                'password' => 'Password@123',
                'email_verified_at' => now(),
                'is_active' => true,
                'is_blocked' => false,
                'lang' => 'ar',
                'investor_type' => InvestorType::Angel,
                'preferred_sector_id' => $sectorIds[0],
                'category_id' => $categoryIds[1],
                'subscription_package_id' => $packageIds[1],
                'available_capital' => 180000.000,
                'capital' => 220000.000,
                'previous_investments_count' => 6,
                'investor_experience' => InvestorExperience::Intermediate,
                'bio' => 'Angel investor focused on early-stage B2B SaaS and operationally strong founders.',
                'short_description' => 'Angel investor in technology and B2B services.',
            ],
            [
                'role' => UserRole::Investor,
                'first_name' => 'Omar',
                'last_name' => 'AlMutairi',
                'display_name' => 'Omar Ventures',
                'country_code' => '965',
                'phone' => '50123457',
                'email' => 'omar.investor@bi.test',
                'password' => 'Password@123',
                'email_verified_at' => now(),
                'is_active' => true,
                'is_blocked' => false,
                'lang' => 'en',
                'investor_type' => InvestorType::Company,
                'preferred_sector_id' => $sectorIds[2],
                'category_id' => $categoryIds[2],
                'subscription_package_id' => $packageIds[2],
                'available_capital' => 950000.000,
                'capital' => 1500000.000,
                'previous_investments_count' => 14,
                'investor_experience' => InvestorExperience::Expert,
                'bio' => 'Corporate investment office interested in logistics, infrastructure, and recurring-revenue businesses.',
                'short_description' => 'Institutional investor with a logistics and infrastructure mandate.',
            ],
            [
                'role' => UserRole::Investor,
                'first_name' => 'Sara',
                'last_name' => 'AlDosari',
                'display_name' => 'Sara Growth Office',
                'country_code' => '965',
                'phone' => '50123458',
                'email' => 'sara.investor@bi.test',
                'password' => 'Password@123',
                'email_verified_at' => now(),
                'is_active' => true,
                'is_blocked' => false,
                'lang' => 'ar',
                'investor_type' => InvestorType::Angel,
                'preferred_sector_id' => $sectorIds[3],
                'category_id' => $categoryIds[3],
                'subscription_package_id' => $packageIds[1],
                'available_capital' => 320000.000,
                'capital' => 400000.000,
                'previous_investments_count' => 9,
                'investor_experience' => InvestorExperience::Expert,
                'bio' => 'Healthcare-focused investor with strong operating and governance experience.',
                'short_description' => 'Operator-investor focused on healthcare and services.',
            ],
            [
                'role' => UserRole::Investor,
                'first_name' => 'Yousef',
                'last_name' => 'AlSabah',
                'display_name' => 'Yousef Family Office',
                'country_code' => '965',
                'phone' => '50123459',
                'email' => 'yousef.investor@bi.test',
                'password' => 'Password@123',
                'email_verified_at' => now(),
                'is_active' => true,
                'is_blocked' => false,
                'lang' => 'en',
                'investor_type' => InvestorType::Company,
                'preferred_sector_id' => $sectorIds[6],
                'category_id' => $categoryIds[7],
                'subscription_package_id' => $packageIds[2],
                'available_capital' => 2500000.000,
                'capital' => 5000000.000,
                'previous_investments_count' => 18,
                'investor_experience' => InvestorExperience::Expert,
                'bio' => 'Family office evaluating cash-generating real estate services and mature SMEs.',
                'short_description' => 'Family office backing mature cash-flow businesses.',
            ],
            [
                'role' => UserRole::Investor,
                'first_name' => 'Laila',
                'last_name' => 'AlFahad',
                'display_name' => 'Laila Seed Circle',
                'country_code' => '965',
                'phone' => '50123460',
                'email' => 'laila.investor@bi.test',
                'password' => 'Password@123',
                'email_verified_at' => now(),
                'is_active' => true,
                'is_blocked' => false,
                'lang' => 'ar',
                'investor_type' => InvestorType::Crowdfunding,
                'preferred_sector_id' => $sectorIds[1],
                'category_id' => $categoryIds[0],
                'subscription_package_id' => $packageIds[0],
                'available_capital' => 45000.000,
                'capital' => 60000.000,
                'previous_investments_count' => 3,
                'investor_experience' => InvestorExperience::Beginner,
                'bio' => 'Emerging investor building exposure through smaller tickets in consumer concepts.',
                'short_description' => 'Entry-level investor focused on consumer opportunities.',
            ],
            [
                'role' => UserRole::Advertiser,
                'first_name' => 'Noura',
                'last_name' => 'AlSaleh',
                'display_name' => 'Noura Hospitality Group',
                'country_code' => '965',
                'phone' => '50123510',
                'email' => 'noura.advertiser@bi.test',
                'password' => 'Password@123',
                'email_verified_at' => now(),
                'is_active' => true,
                'is_blocked' => false,
                'lang' => 'ar',
                'company_license' => 'licenses/noura-hospitality-license.pdf',
                'bio' => 'Operator of multiple food and beverage brands seeking structured growth capital.',
                'short_description' => 'Hospitality operator with expansion plans.',
            ],
            [
                'role' => UserRole::Advertiser,
                'first_name' => 'Faisal',
                'last_name' => 'AlRashid',
                'display_name' => 'Faisal Ventures',
                'country_code' => '965',
                'phone' => '50123511',
                'email' => 'faisal.advertiser@bi.test',
                'password' => 'Password@123',
                'email_verified_at' => now(),
                'is_active' => true,
                'is_blocked' => false,
                'lang' => 'en',
                'company_license' => 'licenses/faisal-ventures-license.pdf',
                'bio' => 'Founder and operator across logistics and service businesses with regional expansion plans.',
                'short_description' => 'Logistics and services advertiser.',
            ],
            [
                'role' => UserRole::Advertiser,
                'first_name' => 'Reem',
                'last_name' => 'AlAjmi',
                'display_name' => 'Reem Healthcare Partners',
                'country_code' => '965',
                'phone' => '50123512',
                'email' => 'reem.advertiser@bi.test',
                'password' => 'Password@123',
                'email_verified_at' => now(),
                'is_active' => true,
                'is_blocked' => false,
                'lang' => 'ar',
                'company_license' => 'licenses/reem-healthcare-license.pdf',
                'bio' => 'Healthcare entrepreneur building multi-branch clinics and premium wellness concepts.',
                'short_description' => 'Healthcare and wellness advertiser.',
            ],
        ];

        foreach ($users as $user) {
            User::query()->create($user);
        }

        $this->command?->info('Demo users seeded: 5 investors and 3 advertisers. Shared password: Password@123');
    }
}
