on:
  push:
    branches:
      - main

name: 🚀 Deploy via SFTP

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4

      - name: 📂 Upload via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: 57.129.140.1
          port: 22
          user: ${{ secrets.ftp_username }}
          pass: ${{ secrets.ftp_password }}
          localDir: "./"
          remoteDir: "/bni"
          reverse: true
