on:
  push:
    branches:
      - main

name: Deploy via SFTP

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📂 Upload via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: 57.129.140.1
          port: 22
          user: ${{ secrets.ftp_username }}
          pass: ${{ secrets.ftp_password }}
          onlyNewer: true
          settings: 'sftp:auto-confirm=yes'
          localDir: './'
          remoteDir: '/public_html/test-deploy'
          reverse: true
          ignoreFile: '.lftp_ignore'
          options: '--verbose'
